In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio

In [2]:
df_cafe = pd.read_csv("dados_ind_faz_talhoes_2014_2025.csv", encoding="utf-8", sep=";")

In [3]:
df_cafe

,codigo_talhao,codigo_fazenda,codigo_produtor,codigo_agroindustria,codigo_consultor,data_plantio,esp_x_m,esp_y_m,numero_plantas_ha,perda,...,89_investimento_em_maquinas_e_equipamento_estoque_de_capital_em_maquinas_e_equipamentos,90_investimento_em_lavouras_estoque_de_capital_em_lavouras,91_investimento_total_estoque_de_capital_sem_terra,92_investimento_total_renda_bruta_da_atividade,93_investimento_total_margem_bruta,94_ponto_de_cobertura_operacional_sacas,95_ponto_de_cobertura_operacional_sacas_ha,96_ponto_de_cobertura_total_sacas,97_ponto_de_cobertura_total_sacas_ha,98_relacao_beneficio_custo
0,22a55bae-8e29-4113-a78b-b11801446a1b,009b75e2-07bd-441d-b1d5-36a3e69397c9,17d5e95c-45fd-45c1-8f91-6c54aacc825f,672258b9-11c7-43b5-b1e0-a44500ea65d2,e2442ad9-2ba3-45f0-a482-a37b00f2608a,16/12/2011,"4,00","0,50",5.000,"0,00",...,"7,29","0,00","3,76","4,28","6,98","738,15","14,20","844,79","16,25","1,85"
1,22baf804-9944-4dc9-8eb8-b11801446a1b,009b75e2-07bd-441d-b1d5-36a3e69397c9,17d5e95c-45fd-45c1-8f91-6c54aacc825f,672258b9-11c7-43b5-b1e0-a44500ea65d2,e2442ad9-2ba3-45f0-a482-a37b00f2608a,16/12/2020,"4,00","0,50",5.000,"0,00",...,"7,29","0,00","3,19","5,14","9,50","825,94","16,52","946,76","18,94","1,32"
2,8a1e1046-a0d0-4e2d-a7e6-b11801446a1b,009b75e2-07bd-441d-b1d5-36a3e69397c9,17d5e95c-45fd-45c1-8f91-6c54aacc825f,672258b9-11c7-43b5-b1e0-a44500ea65d2,e2442ad9-2ba3-45f0-a482-a37b00f2608a,16/12/2021,"4,00","0,50",5.000,"0,00",...,"7,29","0,00","2,97","6,42","13,95","1.976,14","16,13","2.294,55","18,73","1,07"
3,4bd040b2-80a6-43ab-857b-b11801446a1b,009b75e2-07bd-441d-b1d5-36a3e69397c9,17d5e95c-45fd-45c1-8f91-6c54aacc825f,672258b9-11c7-43b5-b1e0-a44500ea65d2,e2442ad9-2ba3-45f0-a482-a37b00f2608a,16/12/2013,"4,00","0,50",5.000,"0,00",...,"7,29","0,00","3,76","3,57","5,35","590,28","16,40","664,11","18,45","1,95"
4,af6291d9-4d43-44d1-a266-b11801446a1b,009b75e2-07bd-441d-b1d5-36a3e69397c9,17d5e95c-45fd-45c1-8f91-6c54aacc825f,672258b9-11c7-43b5-b1e0-a44500ea65d2,e2442ad9-2ba3-45f0-a482-a37b00f2608a,16/12/2018,"3,67","0,70",3.893,"0,00",...,"7,29","0,00","3,76","4,02","6,31","642,85","16,07","724,88","18,12","1,77"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24250,2d89afca-84b5-4d22-ae5c-aae700ef1cdd,ff38fadf-7671-403b-9471-b1617fe1f125,90b4ed4d-dfe4-4081-b4e4-f526a9fbd89b,c7128f41-1e47-47bf-b354-a44500ea981e,f1a42df2-e27d-48c9-ad65-fc45ad2959b8,01/12/2003,"3,70","0,60",4.505,"0,00",...,"93,41","0,00","47,62","15,47","22,57","163,60","21,53","172,86","22,74","2,75"
24251,bc5ad882-c9e6-4d73-908c-aae700ef1cdd,ff38fadf-7671-403b-9471-b1617fe1f125,90b4ed4d-dfe4-4081-b4e4-f526a9fbd89b,c7128f41-1e47-47bf-b354-a44500ea981e,f1a42df2-e27d-48c9-ad65-fc45ad2959b8,01/12/1988,"3,80","0,70",3.759,"0,00",...,"93,41","0,00","47,62","15,48","22,73","293,93","21,77","310,38","22,99","2,72"
24252,6061dfce-92b9-4d26-94eb-aae700ef1cdd,ff38fadf-7671-403b-9471-b1617fe1f125,90b4ed4d-dfe4-4081-b4e4-f526a9fbd89b,c7128f41-1e47-47bf-b354-a44500ea981e,f1a42df2-e27d-48c9-ad65-fc45ad2959b8,01/12/1988,"3,80","0,70",3.759,"0,00",...,"93,41","0,00","47,62","15,55","22,84","238,80","21,71","252,20","22,93","2,71"
24253,c449502d-1d88-4333-9f50-aae700ef1cdd,ff38fadf-7671-403b-9471-b1617fe1f125,90b4ed4d-dfe4-4081-b4e4-f526a9fbd89b,c7128f41-1e47-47bf-b354-a44500ea981e,f1a42df2-e27d-48c9-ad65-fc45ad2959b8,15/12/2018,"3,70","0,60",4.505,"0,00",...,"93,41","0,00","52,39","38,67","113,58","38,44","19,22","40,65","20,33","1,23"
24254,96d9db47-9c9a-4702-8d71-aae700ef1cdd,ff38fadf-7671-403b-9471-b1617fe1f125,90b4ed4d-dfe4-4081-b4e4-f526a9fbd89b,c7128f41-1e47-47bf-b354-a44500ea981e,f1a42df2-e27d-48c9-ad65-fc45ad2959b8,01/12/1988,"3,80","0,70",3.759,"0,00",...,"93,41","0,00","47,62","15,59","23,11","55,06","22,02","58,10","23,24","2,67"

In [4]:
df_cafe.shape

(24255, 126)

In [5]:
len(df_cafe["municipio_fazenda"].unique())

100

In [6]:
len(df_cafe["safra"].unique())

11

In [7]:
len(df_cafe["regiao_sebrae"].unique())

7

In [8]:
variaveis = [
    "5_area_plantada_ha",
    "14_producao_sacas"
]

In [9]:
df_cafe[variaveis]

      5_area_plantada_ha 14_producao_sacas
0                  52,00          1.560,00
1                  50,00          1.250,00
2                 122,50          2.450,00
3                  36,00          1.296,00
4                  40,00          1.280,00
...                  ...               ...
24250               7,60            475,00
24251              13,50            843,00
24252              11,00            684,00
24253               2,00             50,00
24254               2,50            155,00

[24255 rows x 2 columns]

In [10]:
df_cafe['5_area_plantada_ha'] = df_cafe['5_area_plantada_ha'].str.replace('.', '').str.replace(',', '.').astype(float)
df_cafe['14_producao_sacas'] = df_cafe['14_producao_sacas'].str.replace('.', '').str.replace(',', '.').astype(float)
df_cafe['18_produtividade_sacas_ha'] = df_cafe['18_produtividade_sacas_ha'].str.replace('.', '').str.replace(',', '.').astype(float)

In [11]:
df_safra_municipios = df_cafe.groupby(by=["municipio_fazenda", "regiao_sebrae", "safra"])[variaveis].mean().reset_index()
df_safra_municipios["18_produtividade_sacas_ha"] = df_safra_municipios["14_producao_sacas"] / df_safra_municipios["5_area_plantada_ha"]
df_safra_municipios

,municipio_fazenda,regiao_sebrae,safra,5_area_plantada_ha,14_producao_sacas,18_produtividade_sacas_ha
0,Alfenas,Sul,2018/2019,7.368621,208.851724,28.343395
1,Alfenas,Sul,2019/2020,7.307838,283.050811,38.732498
2,Alfenas,Sul,2020/2021,8.502308,212.608846,25.006016
3,Alfenas,Sul,2021/2022,6.740556,64.072222,9.505481
4,Alfenas,Sul,2022/2023,4.065000,215.675000,53.056581
...,...,...,...,...,...,...
608,Viçosa,Zona da Mata e Vertentes,2017/2018,1.565000,41.250000,26.357827
609,Viçosa,Zona da Mata e Vertentes,2018/2019,1.792000,44.600000,24.888393
610,Viçosa,Zona da Mata e Vertentes,2019/2020,1.605556,108.888889,67.820069
611,Viçosa,Zona da Mata e Vertentes,2020/2021,1.907600,39.160000,20.528413
612,Água Boa,Jequitinhonha e Mucuri,2021/2022,8.040000,0.000000,0.000000

In [12]:
df_safra_municipios.to_excel("Dados Educampo - Safras Café.xlsx", index=False)

In [19]:
safras = [
    '2014/2015',
    '2015/2016', '2016/2017', '2017/2018', '2018/2019', '2019/2020',
    '2020/2021', '2021/2022', '2022/2023', '2023/2024', '2024/2025',
]

In [20]:
fig = px.line(
    df_safra_municipios,
    x="safra",
    y="18_produtividade_sacas_ha",
    color="municipio_fazenda",
    markers=True,
    title="Produtividade por Município ao Longo dos Anos"
)

fig.update_layout(
    xaxis_title="Safra",
    yaxis_title="Produtividade (sacas/hectare)",
    legend_title="Município",
    hovermode="x unified"
)

fig.update_xaxes(categoryorder='array', categoryarray=safras)

fig.show()

In [21]:
fig = px.line(
    df_safra_municipios,
    x="safra",
    y="14_producao_sacas",
    color="municipio_fazenda",
    markers=True,
    title="Produção por Município ao Longo dos Anos"
)

fig.update_layout(
    xaxis_title="Safra",
    yaxis_title="Produção (sacas)",
    legend_title="Município",
    hovermode="x unified"
)

fig.update_xaxes(categoryorder='array', categoryarray=safras)

fig.show()

In [22]:
fig = px.line(
    df_safra_municipios,
    x="safra",
    y="5_area_plantada_ha",
    color="municipio_fazenda",
    markers=True,
    title="Área plantada por Município ao Longo dos Anos"
)

fig.update_layout(
    xaxis_title="Safra",
    yaxis_title="Área plantada (hectare)",
    legend_title="Município",
    hovermode="x unified"
)

fig.update_xaxes(categoryorder='array', categoryarray=safras)

fig.show()