In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import unicodedata

In [18]:
df_preco = pd.read_csv("tabela.csv", encoding="ISO-8859-1", sep="\t")
df_educampo = pd.read_excel("Dados Educampo - Safras Café.xlsx")
df_dataset = pd.read_csv("dataset_v17.csv", sep=",")
df_dadosclima = pd.read_csv("Índices Climáticos Anuais Municípios MG 1995-2024 - ERA5.csv", sep=",")

In [19]:
df_preco

,Ano,Janeiro,Fevereiro,Março,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,2025,"376,04","444,27","445,06","444,47","420,01","389,12",NaN,NaN,NaN,NaN,NaN,NaN
1,2024,"197,58","202,5","205,74","223,74","230,3","229,76","219,53","230,37","236,77","259,97","298,22","339,04"
2,2023,"199,83","218,09","211,29","223,02","206,79","191,91","183,3","177,29","162,63","158,18","172,58","188,69"
3,2022,"268,93","285,44","252,79","263,19","254,56","248,68","208,65","209,34","210,58","196,61","174,62","189,21"
4,2021,"119,57",128,"128,62","134,43","153,33","158,15","147,75","146,91","161,35","201,05","231,62","255,5"
5,2020,"120,27","112,9","116,75","109,05","100,66","98,75","101,41","101,67","101,87","92,77","102,02","114,36"
6,2019,"107,04","107,01","101,13","97,74","98,2","110,88","117,05","103,89","101,09","99,45","108,14","125,25"
7,2018,"134,87","132,63","128,66","126,31","123,19","123,18","125,22","117,15","107,23","112,76","113,25","105,41"
8,2017,"161,54","163,06","155,9","153,2","146,12","143,5","159,13","162,52","152,7","136,62","138,43","136,65"
9,2016,"121,39","120,82","135,5","134,36","135,26","145,22","155,8","156,61","155,21","160,15","165,98","149,58"
10,2015,"177,74","165,62","149,16","149,45","144,79","151,12","135,75","135,27","119,6","122,08","117,53","123,18"
11,2014,"115,33","142,68","185,2","193,21","181,83","172,37","169,27","175,89","170,38","187,05","182,75","177,33"
12,2013,"163,49","156,48","151,97","148,82","150,82","130,72","132,13","124,29","121,96","113,4","102,47","107,92"
13,2012,"266,02","258,87","225,65","201,28","194,52","178,69","207,31","198,94","194,55","186,45","168,13","160,54"
14,2011,"242,24","284,31","297,9","319,37","310,14","305,53","284,72","277,05","261,9","259,27","267,47","259,41"
15,2010,"158,75","149,04","149,91","147,21","145,05","158,45","166,5","167,17","169,77","175,63","184,42","203,78"
16,2009,"111,34","113,56","111,49","118,8","127,06","130,84","132,6","145,87","140,08","141,16","157,55","156,53"
17,2008,"144,19","158,58","154,83","144,65","147,13","155,59","164,67","165,86","149,63","115,49","107,79","104,22"
18,2007,"125,42","123,21","117,34","111,42","115,01","121,93","129,25","129,91","133,26","142,94","138,82","142,7"
19,2006,"123,71","117,58","112,64","116,13","96,58",99,"101,27","112,21","112,39","111,24","115,72","130,12"
20,2005,"97,43","109,8","113,78","124,18","117,08","117,46","111,52","113,85","120,98","105,35","108,54","112,51"
21,2004,"69,13","67,56","68,58",67,"69,28","73,37","62,75","61,4","65,58","65,85","75,48","85,07"
22,2003,"53,06","51,75","48,4","55,63","53,65","53,14","56,11","56,6","59,59","57,07","55,86","59,28"
23,2002,"43,22","43,08","47,59","48,52","39,34","35,21","35,63","35,78","36,06","39,03","46,97","46,71"
24,2001,"61,91","59,11","57,68","50,45","54,74","49,09",45,"44,72","40,53","35,04","35,74","39,03"
25,2000,"119,71","108,62","105,41","98,69","92,5","83,07","86,62","83,69","79,65","68,87","63,36","61,49"
26,1999,"113,35","96,59","99,2","97,35","107,94","100,19","87,82","83,47","75,36","94,8","107,52","133,35"
27,1998,"210,73","207,29","177,93","159,14","132,58","118,83","105,89","112,96","99,24","95,8","103,74","112,08"
28,1997,"148,11","180,06","187,05","200,49","207,55","195,49","166,43","179,84","188,01","174,75","192,35","191,22"
29,1996,"136,68","152,71","146,64","135,25","142,68","121,95","100,62","105,52","110,51","109,18","109,13","113,2"
30,1995,"166,07","162,35","170,88","160,77","160,07","147,13","138,32","143,61","131,05","126,92","127,04","116,55"
31,1994,"73,52","77,93","81,85","95,09","119,17","135,16","208,71","189,82","210,26","190,21","169,07","153,06"
32,1993,"69,07","64,23",67,"53,64","57,85","58,05","64,61","73,44","72,62","74,05","73,56","74,42"
33,1992,"54,23","51,54","54,44","49,26","47,47","43,34","53,69","40,48","45,02","58,76","60,84","77,99"
34,1991,"61,51","71,83","76,02","74,13","66,26","62,91","58,69","54,17","61,77","57,89","54,5","46,33"
35,1990,"83,71","98,38","123,52","95,41","90,81","80,65","69,22","85,16","84,85","69,16","57,21","62,47"
36,1989,"120,88","93,55","102,98","126,04","146,41","118,41","78,59","76,94","61,05","54,5","66,49","63,64"
37,1988,"51,54","61,47","63,94","62,57","57,24","70,23","68,22","58,62","69,55","67,96","73,33","100,92"
38,1987,"121,13","101,28","86,61","81,1","84,56","61,42","50,17","47,05","46,01","51,48","49,69","45,2"
39,1986,"309,97","269,09","250,3","214,26","213,39","197,59","205,55","216,12","219,27","194,79","193,02","146,8"
40,1985,"115,81","118,31","120,52","114,37","101,1","89,24","81,04","77,86","74,65","106,83","143,73","245,59"
41,1984,"65,29","64,75","66,91","61,95","62,73","74,16","80,22","73,86","77,59","78,91","80,62","85,99"
42,1983,"93,79","108,39","74,45","68,22","62,15","56,13","51,82","52,24","53,58","54,94","52,16","58,13"
43,1982,"82,07","83,57","85,57","88,19","87,11","96,14","86,87","86,09","83,87","84,66","89,33","99,92"
44,1981,"94,06","93,21","86,67","81,22","76,63","69,93","69,67","74,63","72,29","70,18","73,63","80,41"

In [20]:
df_dataset = df_dataset.drop('Municipio_id', axis=1)

In [21]:
df_dataset["Municipio"] = df_dataset["Municipio"].apply(lambda x: ''.join([c for c in unicodedata.normalize('NFKD', x.split(" - ")[0].replace("ç", "c")) if not unicodedata.combining(c)]))
df_dataset["Municipio"] = df_dataset["Municipio"].apply(lambda x: x.replace(" ", "_"))

In [22]:
df_dadosclima['time'] = pd.to_datetime(df_dadosclima['time'])
df_dadosclima["Ano"] = df_dadosclima["time"].dt.year

In [23]:
df_dadosclima = df_dadosclima.drop('time', axis=1)

In [24]:
df_dadosclima = df_dadosclima[df_dadosclima["Ano"] >= 2012]
df_dadosclima

,Municipio,Base,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,WN22,...,CWD,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,Ano
17,Abadia_dos_Dourados,ERA5,24.02,11.51,35.81,18.75,36,32,76,20,...,15.0,102.0,8,7.18,47.10,118.84,14,710.01,2.53,2012
18,Abadia_dos_Dourados,ERA5,25.38,10.68,34.24,17.83,24,38,57,27,...,21.0,51.0,10,8.18,39.66,106.65,18,621.17,7.85,2013
19,Abadia_dos_Dourados,ERA5,27.01,11.99,38.12,15.38,60,56,111,37,...,15.0,47.0,6,7.81,41.04,106.77,14,503.24,35.15,2014
20,Abadia_dos_Dourados,ERA5,26.15,13.24,37.84,16.91,75,76,122,67,...,15.0,61.0,6,7.48,58.75,142.55,12,644.97,7.43,2015
21,Abadia_dos_Dourados,ERA5,24.55,10.97,34.93,19.64,57,59,119,31,...,21.0,74.0,14,9.91,68.47,162.03,21,707.99,4.58,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12715,Visconde_do_Rio_Branco,ERA5,22.79,9.10,34.08,13.63,29,41,47,14,...,14.0,28.0,21,11.98,144.69,276.72,21,1081.84,41.53,2020
12716,Visconde_do_Rio_Branco,ERA5,23.04,7.75,33.09,14.49,18,26,34,5,...,16.0,28.0,16,9.48,69.98,125.77,17,671.61,23.67,2021
12717,Visconde_do_Rio_Branco,ERA5,22.81,8.48,32.45,15.94,24,18,29,3,...,26.0,73.0,27,12.55,105.57,256.66,27,1043.86,17.05,2022
12718,Visconde_do_Rio_Branco,ERA5,24.80,9.36,35.47,15.47,47,69,61,24,...,13.0,21.0,14,8.13,52.60,119.71,14,881.14,57.14,2023
12719,Visconde_do_Rio_Branco,ERA5,23.26,10.38,33.18,15.10,75,72,65,28,...,15.0,33.0,26,10.26,56.00,138.89,26,826.32,11.04,2024

In [25]:
df_dataset

,target,Ano,altitude,precipitacao (mm) 01,precipitacao (mm) 02,precipitacao (mm) 03,precipitacao (mm) 04,precipitacao (mm) 05,precipitacao (mm) 06,precipitacao (mm) 07,...,temperatura minima (ºC) 05,temperatura minima (ºC) 06,temperatura minima (ºC) 07,temperatura minima (ºC) 08,temperatura minima (ºC) 09,temperatura minima (ºC) 10,temperatura minima (ºC) 11,temperatura minima (ºC) 12,Mesorregião,Municipio
0,5702.0,2012,897,337.500000,39.000000,136.199997,54.099998,99.699997,23.799999,4.100000,...,11.0,11.0,9.0,10.0,12.0,15.0,16.0,16.0,Zona Da Mata,Abre_Campo
1,5702.0,2013,897,257.399994,121.099998,189.800003,90.500000,74.199997,33.500000,13.000000,...,11.0,11.0,9.0,10.0,13.0,14.0,16.0,16.0,Zona Da Mata,Abre_Campo
2,4320.0,2014,897,82.599998,37.000000,120.699997,124.000000,11.100000,8.900000,53.200001,...,11.0,10.0,10.0,10.0,13.0,14.0,16.0,16.0,Zona Da Mata,Abre_Campo
3,6300.0,2015,897,71.300003,205.500000,170.500000,91.500000,95.099998,17.700001,18.700001,...,12.0,11.0,10.0,11.0,13.0,15.0,17.0,17.0,Zona Da Mata,Abre_Campo
4,6300.0,2016,897,327.299988,93.000000,110.400002,58.700001,13.800000,46.400002,3.700000,...,12.0,10.0,9.0,10.0,13.0,15.0,15.0,16.0,Zona Da Mata,Abre_Campo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,3287.0,2020,594,429.100006,239.199997,204.100006,66.900002,44.900002,9.600000,17.000000,...,11.0,11.0,11.0,11.0,14.0,17.0,17.0,17.0,Zona Da Mata,Vermelho_Novo
2050,2208.0,2021,594,119.599998,348.899994,124.199997,55.200001,20.299999,18.000000,2.300000,...,12.0,10.0,8.0,11.0,15.0,16.0,17.0,16.0,Zona Da Mata,Vermelho_Novo
2051,2150.0,2022,594,218.199997,303.500000,29.400000,47.299999,30.100000,3.600000,4.300000,...,11.0,10.0,11.0,11.0,13.0,17.0,16.0,17.0,Zona Da Mata,Vermelho_Novo
2052,3360.0,2023,594,268.600006,67.300003,61.700001,98.500000,30.000000,5.200000,18.100000,...,12.0,11.0,10.0,13.0,16.0,17.0,18.0,18.0,Zona Da Mata,Vermelho_Novo
2053,3157.8,2024,594,329.899994,227.500000,169.100006,71.199997,11.500000,2.300000,5.700000,...,14.0,12.0,11.0,11.0,16.0,17.0,17.0,18.0,Zona Da Mata,Vermelho_Novo

In [26]:
merged_df = pd.merge(df_dadosclima, df_dataset, on=['Municipio', 'Ano'], how='inner')

In [27]:
merged_df = merged_df[list(df_dadosclima.columns) + ["target"]]
merged_df['Ano'] = merged_df['Ano'].astype(int)
merged_df

,Municipio,Base,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,WN22,...,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,Ano,target
0,Alfenas,ERA5,23.91,6.93,33.97,17.33,35,34,60,11,...,41.0,9,7.50,48.20,110.31,12,733.82,40.68,2012,16350.0
1,Alfenas,ERA5,23.26,6.91,33.92,15.63,20,29,42,8,...,24.0,17,9.53,113.99,250.74,22,796.21,56.08,2013,20206.0
2,Alfenas,ERA5,23.94,10.03,36.15,17.03,64,47,97,14,...,37.0,7,6.52,28.52,89.71,11,415.54,48.20,2014,13728.0
3,Alfenas,ERA5,25.71,11.11,35.46,17.78,67,56,91,15,...,29.0,9,8.23,59.12,142.21,16,549.20,28.36,2015,13386.0
4,Alfenas,ERA5,24.04,6.75,34.27,17.46,82,57,81,12,...,47.0,10,8.83,136.39,189.38,13,789.23,38.69,2016,24243.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,Varginha,ERA5,23.26,6.03,36.19,13.68,58,39,54,7,...,73.0,13,8.38,37.10,96.39,17,758.22,15.48,2020,17248.0
1595,Varginha,ERA5,22.89,3.10,34.35,17.92,47,19,48,1,...,90.0,12,8.32,62.92,73.99,17,588.92,8.17,2021,8970.0
1596,Varginha,ERA5,21.66,6.58,33.29,14.96,37,13,29,0,...,60.0,11,8.66,49.24,111.14,16,799.75,19.20,2022,7788.0
1597,Varginha,ERA5,24.09,7.73,37.05,14.69,59,60,58,10,...,33.0,9,8.09,45.09,109.26,15,825.91,32.34,2023,13828.0
1598,Varginha,ERA5,22.64,6.38,35.31,17.39,108,66,70,4,...,37.0,17,9.13,56.07,102.01,20,642.60,14.37,2024,12797.4

In [28]:
len(merged_df["Municipio"].unique())

123

In [87]:
df_result = pd.DataFrame()

In [ ]:
for municipio in merged_df["Municipio"].unique():
    df_municipio = merged_df[merged_df["Municipio"] == municipio]
    numeric_cols = df_municipio.select_dtypes(include=['float64', 'int64']).columns
    corr_matrix = df_municipio[numeric_cols].corr()
    df_result.loc[:, municipio] = corr_matrix["target"]

In [89]:
df_result.fillna(0, inplace=True)

In [ ]:
df_result.loc[:, "MEDIA"] = df_result.mean(axis=1)
df_result.loc[:, "DP"] = df_result.std(axis=1)

C:\Users\josue\AppData\Local\Temp\ipykernel_14316\999824243.py:1: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\josue\AppData\Local\Temp\ipykernel_14316\999824243.py:2: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [91]:
df_result.to_excel("Correlação de variáveis climáticas com produção dos munícipios - ERA5.xlsx")

In [57]:
df_municipio = merged_df[merged_df["Municipio"] == "Alfenas"]

In [61]:
df_municipio

,Municipio,Base,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,WN22,...,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,WSDI,Ano,target
0,Alfenas,Xavier,20.99,3.84,35.03,18.10,45.0,43.0,86.0,0.0,...,15.0,10.03,78.23,116.00,15.0,980.42,31.39,NaN,2012,16350.0
1,Alfenas,Xavier,20.61,4.57,34.41,16.19,27.0,57.0,71.0,0.0,...,17.0,9.54,67.18,124.56,18.0,671.00,124.27,NaN,2013,20206.0
2,Alfenas,Xavier,20.07,4.51,36.88,17.49,68.0,48.0,120.0,0.0,...,6.0,6.85,35.68,99.90,6.0,522.72,45.91,NaN,2014,13728.0
3,Alfenas,Xavier,20.58,7.05,35.71,19.01,68.0,65.0,114.0,0.0,...,9.0,7.43,43.59,108.34,9.0,487.89,17.98,NaN,2015,13386.0
4,Alfenas,Xavier,21.28,1.54,35.30,19.88,78.0,64.0,144.0,0.0,...,19.0,9.36,46.56,133.03,19.0,765.77,48.78,NaN,2016,24243.0
5,Alfenas,Xavier,20.24,4.93,34.82,18.03,40.0,38.0,105.0,0.0,...,7.0,8.01,33.10,83.22,7.0,508.75,13.36,NaN,2017,14566.0
6,Alfenas,Xavier,20.84,5.92,33.53,18.20,38.0,85.0,78.0,0.0,...,8.0,7.70,51.14,83.29,8.0,635.90,51.82,NaN,2018,27265.0
7,Alfenas,Xavier,21.28,3.94,35.13,17.91,70.0,106.0,104.0,0.0,...,12.0,8.34,45.84,83.16,13.0,618.15,33.90,NaN,2019,20208.0
8,Alfenas,Xavier,21.28,6.23,36.91,19.02,45.0,82.0,93.0,0.0,...,19.0,10.45,85.86,190.95,19.0,862.59,13.00,NaN,2020,21750.0
9,Alfenas,Xavier,20.79,2.54,35.92,18.39,49.0,62.0,95.0,0.0,...,19.0,9.98,52.21,102.02,19.0,777.51,11.56,NaN,2021,13399.0
10,Alfenas,Xavier,20.70,5.31,33.70,14.87,29.0,80.0,70.0,0.0,...,22.0,9.70,34.11,142.95,22.0,848.73,14.21,NaN,2022,9170.0
11,Alfenas,Xavier,22.58,7.78,37.29,16.44,52.0,143.0,101.0,2.0,...,17.0,9.12,48.75,136.09,17.0,961.58,34.82,NaN,2023,22190.0

In [59]:
numeric_cols = df_municipio.select_dtypes(include=['float64', 'int64']).columns
corr_matrix = df_municipio[numeric_cols].corr()
corr_matrix.dropna(axis=1, how='all', inplace=True)
corr_matrix.dropna(axis=0, how='all', inplace=True)
fig = px.imshow(
    corr_matrix,
    color_continuous_scale='RdBu_r',
    zmin=-1, zmax=1,
    labels=dict(color='Correlação'),
    title="Mapa de calor de correlação de variáveis",
    width=1200,
    height=1000
)
fig.show()
pio.write_html(fig, file="Correlação de Variáveis - Dados Xavier - Alfenas.html", auto_open=True)