In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
import unicodedata

In [11]:
df_dados_correlacao = pd.read_excel("Dados para correlação v2 - Xavier.xlsx")

In [12]:
df_dados_correlacao

,Municipio,Ano,target_por_area,preco_6,TNx_6,TNn_6,TXx_6,TXn_6,TX90p_6,Tn90p_6,...,CWD_5,CDD_5,Wet20mm_5,Prec-Intensity_5,rx1day_5,rx5day_5,r95p_5,pr-wet-qrt_5,pr-dry-qrt_5,WSDI_5
0,Alfenas,2012,1.500000,305.53,11.99,1.86,27.07,17.71,2,0,...,5,10,0,5.20,11.87,43.83,0,453.14,285.27,NaN
1,Alfenas,2013,1.980010,178.69,16.77,8.13,27.52,18.89,2,9,...,5,22,2,8.43,23.03,53.02,2,242.45,218.41,NaN
2,Alfenas,2014,1.320000,130.72,16.47,8.40,26.46,19.47,0,11,...,2,22,0,5.41,10.05,18.12,0,237.45,156.96,NaN
3,Alfenas,2015,1.380000,172.37,13.80,6.39,27.66,21.57,4,1,...,3,9,0,5.45,13.54,20.52,0,298.16,248.75,NaN
4,Alfenas,2016,2.249930,151.12,14.95,7.05,27.40,19.49,4,4,...,6,16,0,4.84,13.44,19.23,0,387.29,248.27,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,Varginha,2019,1.560044,123.18,15.96,8.88,28.25,19.30,6,12,...,2,17,1,20.38,35.46,41.03,1,390.38,238.24,NaN
1472,Varginha,2020,1.899978,110.88,15.41,5.79,28.05,20.85,5,11,...,3,7,0,3.65,11.40,15.89,0,513.86,123.15,NaN
1473,Varginha,2021,1.200000,98.75,16.64,8.25,28.24,21.54,9,7,...,3,12,0,2.66,5.01,9.87,0,267.50,146.14,NaN
1474,Varginha,2022,1.020039,158.15,16.14,6.16,27.42,17.08,5,8,...,2,15,0,4.45,6.76,12.63,0,290.67,104.26,NaN
1475,Varginha,2023,1.679990,248.68,15.66,5.75,28.44,20.85,6,6,...,2,29,0,2.45,3.87,4.90,0,328.74,203.98,NaN

In [13]:
numeric_cols = df_dados_correlacao.select_dtypes(include=['float64', 'int64']).columns
corr_matrix = df_dados_correlacao[numeric_cols].corr()

In [14]:
corr_matrix

,Ano,target_por_area,preco_6,TNx_6,TNn_6,TXx_6,TXn_6,TX90p_6,Tn90p_6,WD30_6,...,CWD_5,CDD_5,Wet20mm_5,Prec-Intensity_5,rx1day_5,rx5day_5,r95p_5,pr-wet-qrt_5,pr-dry-qrt_5,WSDI_5
Ano,1.000000,-0.003377,-0.304823,0.128651,-0.100848,0.153316,0.190501,0.412579,-0.032681,0.007399,...,-0.353407,0.165025,-0.357301,-0.130458,-0.373244,-0.434407,-0.360203,0.167197,-0.344570,NaN
target_por_area,-0.003377,1.000000,-0.012584,0.032792,0.010880,0.181586,0.219785,0.104144,-0.091623,0.199128,...,-0.006315,-0.001358,-0.051788,0.044387,-0.000212,-0.005993,-0.044566,0.107487,0.012548,NaN
preco_6,-0.304823,-0.012584,1.000000,-0.260065,-0.284792,-0.139070,-0.210162,-0.208507,-0.466316,-0.016286,...,0.036857,0.030431,0.150036,0.162814,0.159374,0.235096,0.160241,-0.165546,0.183934,NaN
TNx_6,0.128651,0.032792,-0.260065,1.000000,0.610619,0.651441,0.409238,0.036944,0.475475,0.321579,...,0.012401,0.119306,-0.009131,0.033294,-0.013288,0.026017,0.008220,-0.143503,-0.100876,NaN
TNn_6,-0.100848,0.010880,-0.284792,0.610619,1.000000,0.550110,0.526033,0.078035,0.476122,0.246725,...,-0.101861,0.169951,-0.009498,-0.019086,-0.051405,-0.089066,-0.000152,0.041709,0.058936,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rx5day_5,-0.434407,-0.005993,0.235096,0.026017,-0.089066,-0.129237,-0.068100,-0.221469,0.052753,-0.034927,...,0.512561,-0.176094,0.791705,0.638119,0.861314,1.000000,0.778745,0.131892,0.494472,NaN
r95p_5,-0.360203,-0.044566,0.160241,0.008220,-0.000152,-0.118134,0.036918,-0.187838,0.022261,-0.027319,...,0.357942,-0.096475,0.961674,0.606244,0.800245,0.778745,1.000000,0.166034,0.431711,NaN
pr-wet-qrt_5,0.167197,0.107487,-0.165546,-0.143503,0.041709,-0.061500,0.178598,0.193247,0.080885,-0.073195,...,0.126247,-0.072239,0.201930,0.231565,0.231323,0.131892,0.166034,1.000000,0.632761,NaN
pr-dry-qrt_5,-0.344570,0.012548,0.183934,-0.100876,0.058936,-0.132001,-0.016340,-0.018299,0.160547,-0.038194,...,0.352550,-0.090430,0.458510,0.415637,0.517946,0.494472,0.431711,0.632761,1.000000,NaN
WSDI_5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
corr_matrix.to_excel("Matriz de correlação v2 - Xavier.xlsx")

In [16]:
df_corr_target = corr_matrix["target_por_area"]
df_corr_target.describe()

count    307.000000
mean       0.031905
std        0.130125
min       -0.290053
25%       -0.047167
50%        0.015948
75%        0.103462
max        1.000000
Name: target_por_area, dtype: float64

In [17]:
q_75 = df_corr_target.quantile(0.75)
top_25 = df_corr_target[df_corr_target >= q_75]
top_25

target_por_area    1.000000
TXx_6              0.181586
TXn_6              0.219785
TX90p_6            0.104144
WD30_6             0.199128
                     ...
TXn_5              0.104087
WD30_5             0.154793
Tn10p_5            0.202521
TXMCD_5            0.264797
pr-wet-qrt_5       0.107487
Name: target_por_area, Length: 77, dtype: float64

In [18]:
top_25.sort_values(ascending=False, inplace=True)

In [19]:
top_25.to_excel("Top 25 variáveis mais significativas v2 - Xavier.xlsx")