In [1]:
import os
import pandas as pd

In [22]:
df_faltantes = pd.DataFrame()

In [23]:
for file in os.listdir("faltantes"):
    municipio = file.split("-MG")[0]
    df_municipio = pd.read_csv(f"faltantes/{file}", sep=",")
    df_municipio.loc[:, "Municipio"] = municipio
    df_municipio.loc[:, "Base"] = "Xavier"
    df_faltantes = pd.concat([df_faltantes, df_municipio])

In [24]:
df_faltantes

,time,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,WN22,Frost,...,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,Municipio,Base
0,1995-01-01,19.83,15.90,33.01,24.87,8.0,1.0,15.0,0.0,0.0,...,21.0,1.0,7.78,33.45,44.94,1.0,699.81,641.48,Santa_Barbara_do_Leste,Xavier
1,1995-02-01,18.97,16.59,31.53,23.13,1.0,0.0,6.0,0.0,0.0,...,7.0,2.0,8.91,30.71,77.93,3.0,737.48,644.42,Santa_Barbara_do_Leste,Xavier
2,1995-03-01,20.03,14.53,31.40,21.13,2.0,2.0,7.0,0.0,0.0,...,5.0,0.0,6.41,16.67,36.75,0.0,542.45,291.10,Santa_Barbara_do_Leste,Xavier
3,1995-04-01,18.46,12.88,28.20,22.60,0.0,1.0,0.0,0.0,0.0,...,8.0,1.0,9.07,38.81,41.21,1.0,351.78,310.57,Santa_Barbara_do_Leste,Xavier
4,1995-05-01,17.95,8.21,27.91,21.11,0.0,7.0,0.0,0.0,0.0,...,9.0,0.0,4.74,18.54,25.37,0.0,250.13,208.29,Santa_Barbara_do_Leste,Xavier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,2023-11-01,21.91,13.87,36.88,25.02,12.0,17.0,20.0,0.0,0.0,...,10.0,2.0,9.72,22.51,60.69,2.0,431.94,351.28,Turvolandia,Xavier
347,2023-12-01,20.96,16.85,33.80,26.41,13.0,11.0,22.0,0.0,0.0,...,4.0,1.0,7.74,21.90,61.75,1.0,517.38,441.57,Turvolandia,Xavier
348,2024-01-01,21.21,15.41,33.36,24.00,2.0,11.0,18.0,0.0,0.0,...,2.0,3.0,9.48,36.48,60.10,3.0,542.89,475.29,Turvolandia,Xavier
349,2024-02-01,21.43,16.03,32.15,23.31,1.0,13.0,13.0,0.0,0.0,...,2.0,1.0,9.86,25.85,87.24,1.0,625.98,526.78,Turvolandia,Xavier
350,2024-03-01,20.82,18.20,33.66,29.69,9.0,17.0,19.0,0.0,0.0,...,5.0,0.0,6.08,18.49,45.40,0.0,627.14,596.52,Turvolandia,Xavier

In [25]:
df_dadosxavier = pd.read_csv("dados_xavier/Índices Climáticos Mensais Municípios MG 1995-2024 - Xavier.csv", sep=",")

In [26]:
df_dadosxavier

,Municipio,Base,time,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,...,CWD,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,WSDI
0,Abadia_dos_Dourados,Xavier,1995-01-01,21.86,19.40,35.06,26.13,9.0,10.0,20.0,...,12.0,7.0,1.0,6.31,29.47,55.97,1.0,594.63,512.05,6.0
1,Abadia_dos_Dourados,Xavier,1995-02-01,21.06,18.87,32.91,25.98,4.0,2.0,11.0,...,16.0,7.0,8.0,17.48,52.19,145.77,8.0,745.62,714.90,0.0
2,Abadia_dos_Dourados,Xavier,1995-03-01,21.66,17.86,33.25,27.54,2.0,7.0,18.0,...,4.0,3.0,1.0,8.30,33.78,56.84,1.0,691.49,658.59,0.0
3,Abadia_dos_Dourados,Xavier,1995-04-01,20.94,13.83,30.75,23.86,0.0,6.0,8.0,...,3.0,8.0,1.0,6.04,25.28,61.55,1.0,639.84,564.72,0.0
4,Abadia_dos_Dourados,Xavier,1995-05-01,19.73,12.07,31.07,24.34,3.0,11.0,4.0,...,4.0,16.0,2.0,20.92,65.81,120.63,2.0,503.95,351.03,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148819,Visconde_do_Rio_Branco,Xavier,2023-11-01,24.66,15.59,39.99,26.12,12.0,18.0,22.0,...,6.0,10.0,1.0,7.73,21.11,101.32,2.0,332.70,307.63,NaN
148820,Visconde_do_Rio_Branco,Xavier,2023-12-01,23.02,19.90,36.33,24.60,12.0,18.0,27.0,...,6.0,5.0,1.0,7.81,28.81,52.17,1.0,484.92,353.20,NaN
148821,Visconde_do_Rio_Branco,Xavier,2024-01-01,23.90,18.72,35.99,21.83,4.0,19.0,23.0,...,6.0,2.0,8.0,14.25,45.90,109.96,8.0,622.23,520.03,NaN
148822,Visconde_do_Rio_Branco,Xavier,2024-02-01,23.18,20.31,35.10,25.72,3.0,13.0,24.0,...,6.0,2.0,3.0,11.46,34.11,85.72,3.0,755.71,592.66,NaN
148823,Visconde_do_Rio_Branco,Xavier,2024-03-01,24.48,20.75,36.57,29.93,6.0,17.0,19.0,...,6.0,5.0,2.0,12.17,28.02,65.65,2.0,763.97,755.49,NaN

In [27]:
df_dadosxavier = pd.concat([df_dadosxavier, df_faltantes])

In [28]:
df_dadosxavier[df_dadosxavier["Municipio"] == "Sao_Domingos_das_Dores"]

,Municipio,Base,time,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,...,CWD,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,WSDI
0,Sao_Domingos_das_Dores,Xavier,1995-01-01,20.46,16.91,35.06,26.66,15.0,4.0,20.0,...,3.0,21.0,1.0,8.54,20.65,35.47,1.0,520.26,496.71,NaN
1,Sao_Domingos_das_Dores,Xavier,1995-02-01,19.32,17.11,31.79,23.74,1.0,0.0,13.0,...,9.0,12.0,3.0,16.15,63.89,114.54,3.0,603.12,475.15,NaN
2,Sao_Domingos_das_Dores,Xavier,1995-03-01,20.58,14.89,31.69,21.54,0.0,2.0,10.0,...,2.0,7.0,2.0,9.40,24.02,37.22,2.0,398.91,299.27,NaN
3,Sao_Domingos_das_Dores,Xavier,1995-04-01,18.65,13.49,28.54,22.60,0.0,1.0,0.0,...,3.0,10.0,1.0,11.60,29.66,31.79,1.0,356.81,324.81,NaN
4,Sao_Domingos_das_Dores,Xavier,1995-05-01,18.29,8.39,28.17,21.47,0.0,5.0,0.0,...,1.0,9.0,1.0,10.40,33.56,45.43,1.0,232.09,181.56,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Sao_Domingos_das_Dores,Xavier,2023-11-01,21.91,14.13,37.08,27.23,16.0,18.0,19.0,...,2.0,14.0,1.0,9.99,28.89,47.98,1.0,216.46,194.13,NaN
347,Sao_Domingos_das_Dores,Xavier,2023-12-01,22.87,18.08,34.79,27.19,20.0,24.0,22.0,...,7.0,9.0,0.0,8.32,16.80,49.63,0.0,352.94,196.63,NaN
348,Sao_Domingos_das_Dores,Xavier,2024-01-01,22.44,19.11,34.48,23.33,7.0,25.0,14.0,...,11.0,9.0,7.0,16.64,40.21,146.85,7.0,548.48,383.80,NaN
349,Sao_Domingos_das_Dores,Xavier,2024-02-01,21.98,17.66,32.64,24.58,4.0,13.0,15.0,...,9.0,6.0,4.0,12.54,33.34,97.48,5.0,675.25,553.47,NaN
350,Sao_Domingos_das_Dores,Xavier,2024-03-01,24.13,19.85,35.06,28.61,11.0,18.0,16.0,...,3.0,7.0,0.0,7.35,15.56,30.29,0.0,697.92,657.49,NaN

In [29]:
df_dadosxavier.to_csv("dados_xavier/Índices Climáticos Mensais Municípios MG 1995-2024 - Xavier v2.csv", sep=",", index=False)