In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df_cafe = pd.read_excel("dados_educampo/Dados Café - Primeira planilha.xlsx")
df_ibge = pd.read_excel("dados_ibge/Indicadores IBGE por Mesorregião - 2019 a 2023.xlsx")

In [4]:
df_cafe

,Região,Agroindústria,Consultor,Fazenda,Talhão,Cod. Talhao,Data Plantio,Estagio,Tipo de poda,Esp X,...,89. Investimento em máquinas e equipamento/estoque de capital em máquinas e equipamentos (%),90. Investimento em lavouras/estoque de capital em lavouras (%),91. Investimento total/estoque de capital sem terra (%),92. Investimento total/renda bruta da atividade (%),93. Investimento total/margem bruta (%),94. Ponto de cobertura operacional (sacas),95. Ponto de cobertura operacional (sacas/hectare),96. Ponto de cobertura total (sacas),97. Ponto de cobertura total (sacas/hectare),98. Relação benefício/custo (R$)
0,Cerrado,Agroindustria 1,Consultor 01,Fazenda 001,Talhao 0001,9affa277-d657-4563-b955-a71d00af986e,2013-01-01,Produção,Sem poda,3.8,...,21.66,NaN,6.90,4.31,7.20,1336.08,21.52,1440.95,23.21,1.94
1,Cerrado,Agroindustria 1,Consultor 01,Fazenda 001,Talhao 0002,097f016e-844e-4b27-ad3f-a71d00b09f20,2014-01-01,Produção,Sem poda,3.8,...,21.66,NaN,6.49,4.72,7.62,1053.26,18.63,1151.70,20.37,1.96
2,Cerrado,Agroindustria 1,Consultor 01,Fazenda 001,Talhao 0003,c1dbbfbe-e34f-4042-9661-a71d00afe953,2013-01-01,Produção,Sem poda,3.8,...,21.66,NaN,6.90,5.19,8.59,1532.45,17.70,1674.52,19.34,1.88
3,Cerrado,Agroindustria 1,Consultor 01,Fazenda 001,Talhao 0004,500f0c4b-8663-4511-ba55-a71d00b33dca,2013-01-01,Produção,Sem poda,3.8,...,21.66,NaN,8.73,7.46,18.63,1312.22,18.95,1407.25,20.32,1.32
4,Cerrado,Agroindustria 1,Consultor 01,Fazenda 001,Talhao 0005,d17b2790-7027-474b-b08c-a71d00af1e6f,2008-01-01,Produção,Sem poda,3.8,...,11.49,NaN,5.38,4.27,7.56,758.24,23.84,830.05,26.10,1.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3299,Matas,Agroindustria 7,Consultor 09,Fazenda 356,Talhao 3300,2f84103d-b8a2-4f61-b129-a44501093c12,2002-01-01,Produção,Sem poda,2.2,...,53.88,NaN,9.10,9.83,41.25,146.00,20.22,156.05,21.61,0.99
3300,Matas,Agroindustria 7,Consultor 09,Fazenda 356,Talhao 3301,855352e2-9520-47a7-a966-a44501093c12,2002-01-01,Produção,Sem poda,2.2,...,53.88,NaN,9.86,12.93,89.37,48.17,17.33,51.70,18.60,0.87
3301,Matas,Agroindustria 7,Consultor 09,Fazenda 356,Talhao 3302,ce5b15e0-18a7-451b-af1c-a44501093c12,2002-01-01,Produção,Sem poda,2.2,...,53.88,NaN,9.86,14.27,135.17,56.58,16.55,60.93,17.81,0.82
3302,Matas,Agroindustria 7,Consultor 09,Fazenda 356,Talhao 3303,e3391f2e-2276-4daf-9e24-ac9b0122f20d,1988-01-24,Produção,Sem poda,1.9,...,53.88,NaN,8.43,13.33,-3750.23,116.96,16.85,127.40,18.36,0.86
3303,Matas,Agroindustria 7,Consultor 09,Fazenda 356,Talhao 3304,2371749e-df47-452a-b3d3-ac9b0122f20d,2000-11-24,Produção,Sem poda,2.5,...,53.88,NaN,8.43,14.19,333.04,56.16,14.70,61.71,16.15,0.89

In [5]:
df_ibge

,Mesorregião,Produto,Ano,Área destinada à colheita (Hectares),Área colhida (Hectares),Quantidade produzida (Toneladas),Rendimento médio da produção (Quilogramas por Hectare),Valor da produção (Mil Reais)
0,Noroeste de Minas (MG),Café (em grão) Total,2019,16255,16255,37969,2336,254593
1,Noroeste de Minas (MG),Café (em grão) Total,2020,17744,17744,43805,2469,356546
2,Noroeste de Minas (MG),Café (em grão) Total,2021,19008,19008,43050,2265,609797
3,Noroeste de Minas (MG),Café (em grão) Total,2022,19051,19051,44758,2349,928473
4,Noroeste de Minas (MG),Café (em grão) Total,2023,19960,19960,51098,2560,712682
...,...,...,...,...,...,...,...,...
175,Zona da Mata (MG),Café (em grão) Canephora,2019,505,505,1068,2115,5065
176,Zona da Mata (MG),Café (em grão) Canephora,2020,522,522,1233,2362,6623
177,Zona da Mata (MG),Café (em grão) Canephora,2021,504,504,1069,2121,8679
178,Zona da Mata (MG),Café (em grão) Canephora,2022,488,488,1340,2746,15327
179,Zona da Mata (MG),Café (em grão) Canephora,2023,498,498,1181,2371,10643

In [20]:
df_ibge["Mesorregião"].unique()

array(['Noroeste de Minas (MG)', 'Norte de Minas (MG)',
       'Jequitinhonha (MG)', 'Vale do Mucuri (MG)',
       'Triângulo Mineiro/Alto Paranaíba (MG)', 'Central Mineira (MG)',
       'Metropolitana de Belo Horizonte (MG)', 'Vale do Rio Doce (MG)',
       'Oeste de Minas (MG)', 'Sul/Sudoeste de Minas (MG)',
       'Campo das Vertentes (MG)', 'Zona da Mata (MG)'], dtype=object)

In [ ]:
# Cerrado
df_ibge.loc[(df_ibge["Mesorregião"].isin(["Triângulo Mineiro/Alto Paranaíba (MG)", "Noroeste de Minas (MG)"])) & (df_ibge["Produto"] == "Café (em grão) Total") & (df_ibge["Ano"] == 2022)]

,Mesorregião,Produto,Ano,Área destinada à colheita (Hectares),Área colhida (Hectares),Quantidade produzida (Toneladas),Rendimento médio da produção (Quilogramas por Hectare),Valor da produção (Mil Reais)
3,Noroeste de Minas (MG),Café (em grão) Total,2022,19051,19051,44758,2349,928473
63,Triângulo Mineiro/Alto Paranaíba (MG),Café (em grão) Total,2022,185247,185247,272595,1472,5662800

In [ ]:
# Matas
df_ibge.loc[(df_ibge["Mesorregião"].isin(["Zona da Mata (MG)", "Vale do Rio Doce (MG)", "Central Mineira (MG)"])) & (df_ibge["Produto"] == "Café (em grão) Total") & (df_ibge["Ano"] == 2022)]

,Mesorregião,Produto,Ano,Área destinada à colheita (Hectares),Área colhida (Hectares),Quantidade produzida (Toneladas),Rendimento médio da produção (Quilogramas por Hectare),Valor da produção (Mil Reais)
78,Central Mineira (MG),Café (em grão) Total,2022,796,796,1748,2196,36035
108,Vale do Rio Doce (MG),Café (em grão) Total,2022,66881,66881,100848,1508,1861915
168,Zona da Mata (MG),Café (em grão) Total,2022,203218,203218,272694,1342,5573387

In [27]:
# Sul
df_ibge.loc[(df_ibge["Mesorregião"].isin(["Sul/Sudoeste de Minas (MG)"])) & (df_ibge["Produto"] == "Café (em grão) Total") & (df_ibge["Ano"] == 2022)]

,Mesorregião,Produto,Ano,Área destinada à colheita (Hectares),Área colhida (Hectares),Quantidade produzida (Toneladas),Rendimento médio da produção (Quilogramas por Hectare),Valor da produção (Mil Reais)
138,Sul/Sudoeste de Minas (MG),Café (em grão) Total,2022,420822,420822,521753,1240,10723427

In [24]:
df_cafe.loc[(df_cafe["Região"] == "Sul"), "6. Área em produção (hectare)"].sum()

np.float64(13661.12)

In [25]:
df_cafe.loc[(df_cafe["Região"] == "Sul"), "18. Produtividade  (sacas/hectare)"].mean()

np.float64(23.086035665294926)

In [29]:
df_cafe.loc[(df_cafe["Região"] == "Sul"), "14. Produção (sacas)"].sum()

np.float64(298826.5)