In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
import unicodedata

In [24]:
df_preco = pd.read_csv("dados_ibge/Dados de preço de café.csv", encoding="ISO-8859-1", sep="\t")
df_dataset_vsemarea = pd.read_csv("dados_ibge/Dados Marcos.csv", sep=",")
df_dataset_vcomarea = pd.read_csv("dados_ibge/Dados Marcos com área.csv", sep=",")
df_dadosclima = pd.read_csv("dados_xavier/Índices Climáticos Mensais Municípios MG 1995-2024 - Xavier v2.csv", sep=",")

In [25]:
df_preco

,Ano,Janeiro,Fevereiro,Março,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,2025,"376,04","444,27","445,06","444,47","420,01","389,12",NaN,NaN,NaN,NaN,NaN,NaN
1,2024,"197,58","202,5","205,74","223,74","230,3","229,76","219,53","230,37","236,77","259,97","298,22","339,04"
2,2023,"199,83","218,09","211,29","223,02","206,79","191,91","183,3","177,29","162,63","158,18","172,58","188,69"
3,2022,"268,93","285,44","252,79","263,19","254,56","248,68","208,65","209,34","210,58","196,61","174,62","189,21"
4,2021,"119,57",128,"128,62","134,43","153,33","158,15","147,75","146,91","161,35","201,05","231,62","255,5"
5,2020,"120,27","112,9","116,75","109,05","100,66","98,75","101,41","101,67","101,87","92,77","102,02","114,36"
6,2019,"107,04","107,01","101,13","97,74","98,2","110,88","117,05","103,89","101,09","99,45","108,14","125,25"
7,2018,"134,87","132,63","128,66","126,31","123,19","123,18","125,22","117,15","107,23","112,76","113,25","105,41"
8,2017,"161,54","163,06","155,9","153,2","146,12","143,5","159,13","162,52","152,7","136,62","138,43","136,65"
9,2016,"121,39","120,82","135,5","134,36","135,26","145,22","155,8","156,61","155,21","160,15","165,98","149,58"
10,2015,"177,74","165,62","149,16","149,45","144,79","151,12","135,75","135,27","119,6","122,08","117,53","123,18"
11,2014,"115,33","142,68","185,2","193,21","181,83","172,37","169,27","175,89","170,38","187,05","182,75","177,33"
12,2013,"163,49","156,48","151,97","148,82","150,82","130,72","132,13","124,29","121,96","113,4","102,47","107,92"
13,2012,"266,02","258,87","225,65","201,28","194,52","178,69","207,31","198,94","194,55","186,45","168,13","160,54"
14,2011,"242,24","284,31","297,9","319,37","310,14","305,53","284,72","277,05","261,9","259,27","267,47","259,41"
15,2010,"158,75","149,04","149,91","147,21","145,05","158,45","166,5","167,17","169,77","175,63","184,42","203,78"
16,2009,"111,34","113,56","111,49","118,8","127,06","130,84","132,6","145,87","140,08","141,16","157,55","156,53"
17,2008,"144,19","158,58","154,83","144,65","147,13","155,59","164,67","165,86","149,63","115,49","107,79","104,22"
18,2007,"125,42","123,21","117,34","111,42","115,01","121,93","129,25","129,91","133,26","142,94","138,82","142,7"
19,2006,"123,71","117,58","112,64","116,13","96,58",99,"101,27","112,21","112,39","111,24","115,72","130,12"
20,2005,"97,43","109,8","113,78","124,18","117,08","117,46","111,52","113,85","120,98","105,35","108,54","112,51"
21,2004,"69,13","67,56","68,58",67,"69,28","73,37","62,75","61,4","65,58","65,85","75,48","85,07"
22,2003,"53,06","51,75","48,4","55,63","53,65","53,14","56,11","56,6","59,59","57,07","55,86","59,28"
23,2002,"43,22","43,08","47,59","48,52","39,34","35,21","35,63","35,78","36,06","39,03","46,97","46,71"
24,2001,"61,91","59,11","57,68","50,45","54,74","49,09",45,"44,72","40,53","35,04","35,74","39,03"
25,2000,"119,71","108,62","105,41","98,69","92,5","83,07","86,62","83,69","79,65","68,87","63,36","61,49"
26,1999,"113,35","96,59","99,2","97,35","107,94","100,19","87,82","83,47","75,36","94,8","107,52","133,35"
27,1998,"210,73","207,29","177,93","159,14","132,58","118,83","105,89","112,96","99,24","95,8","103,74","112,08"
28,1997,"148,11","180,06","187,05","200,49","207,55","195,49","166,43","179,84","188,01","174,75","192,35","191,22"
29,1996,"136,68","152,71","146,64","135,25","142,68","121,95","100,62","105,52","110,51","109,18","109,13","113,2"
30,1995,"166,07","162,35","170,88","160,77","160,07","147,13","138,32","143,61","131,05","126,92","127,04","116,55"
31,1994,"73,52","77,93","81,85","95,09","119,17","135,16","208,71","189,82","210,26","190,21","169,07","153,06"
32,1993,"69,07","64,23",67,"53,64","57,85","58,05","64,61","73,44","72,62","74,05","73,56","74,42"
33,1992,"54,23","51,54","54,44","49,26","47,47","43,34","53,69","40,48","45,02","58,76","60,84","77,99"
34,1991,"61,51","71,83","76,02","74,13","66,26","62,91","58,69","54,17","61,77","57,89","54,5","46,33"
35,1990,"83,71","98,38","123,52","95,41","90,81","80,65","69,22","85,16","84,85","69,16","57,21","62,47"
36,1989,"120,88","93,55","102,98","126,04","146,41","118,41","78,59","76,94","61,05","54,5","66,49","63,64"
37,1988,"51,54","61,47","63,94","62,57","57,24","70,23","68,22","58,62","69,55","67,96","73,33","100,92"
38,1987,"121,13","101,28","86,61","81,1","84,56","61,42","50,17","47,05","46,01","51,48","49,69","45,2"
39,1986,"309,97","269,09","250,3","214,26","213,39","197,59","205,55","216,12","219,27","194,79","193,02","146,8"
40,1985,"115,81","118,31","120,52","114,37","101,1","89,24","81,04","77,86","74,65","106,83","143,73","245,59"
41,1984,"65,29","64,75","66,91","61,95","62,73","74,16","80,22","73,86","77,59","78,91","80,62","85,99"
42,1983,"93,79","108,39","74,45","68,22","62,15","56,13","51,82","52,24","53,58","54,94","52,16","58,13"
43,1982,"82,07","83,57","85,57","88,19","87,11","96,14","86,87","86,09","83,87","84,66","89,33","99,92"
44,1981,"94,06","93,21","86,67","81,22","76,63","69,93","69,67","74,63","72,29","70,18","73,63","80,41"

In [26]:
df_dataset_vsemarea

,target,Municipio_id,Ano,altitude,precipitacao (mm) 01,precipitacao (mm) 02,precipitacao (mm) 03,precipitacao (mm) 04,precipitacao (mm) 05,precipitacao (mm) 06,...,temperatura minima (ºC) 05,temperatura minima (ºC) 06,temperatura minima (ºC) 07,temperatura minima (ºC) 08,temperatura minima (ºC) 09,temperatura minima (ºC) 10,temperatura minima (ºC) 11,temperatura minima (ºC) 12,Mesorregião,Municipio
0,5702.0,3100302,2012,897,337.500000,39.000000,136.199997,54.099998,99.699997,23.799999,...,11.0,11.0,9.0,10.0,12.0,15.0,16.0,16.0,Zona Da Mata,Abre Campo - MG
1,5702.0,3100302,2013,897,257.399994,121.099998,189.800003,90.500000,74.199997,33.500000,...,11.0,11.0,9.0,10.0,13.0,14.0,16.0,16.0,Zona Da Mata,Abre Campo - MG
2,4320.0,3100302,2014,897,82.599998,37.000000,120.699997,124.000000,11.100000,8.900000,...,11.0,10.0,10.0,10.0,13.0,14.0,16.0,16.0,Zona Da Mata,Abre Campo - MG
3,6300.0,3100302,2015,897,71.300003,205.500000,170.500000,91.500000,95.099998,17.700001,...,12.0,11.0,10.0,11.0,13.0,15.0,17.0,17.0,Zona Da Mata,Abre Campo - MG
4,6300.0,3100302,2016,897,327.299988,93.000000,110.400002,58.700001,13.800000,46.400002,...,12.0,10.0,9.0,10.0,13.0,15.0,15.0,16.0,Zona Da Mata,Abre Campo - MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,3287.0,3171154,2020,594,429.100006,239.199997,204.100006,66.900002,44.900002,9.600000,...,11.0,11.0,11.0,11.0,14.0,17.0,17.0,17.0,Zona Da Mata,Vermelho Novo - MG
2050,2208.0,3171154,2021,594,119.599998,348.899994,124.199997,55.200001,20.299999,18.000000,...,12.0,10.0,8.0,11.0,15.0,16.0,17.0,16.0,Zona Da Mata,Vermelho Novo - MG
2051,2150.0,3171154,2022,594,218.199997,303.500000,29.400000,47.299999,30.100000,3.600000,...,11.0,10.0,11.0,11.0,13.0,17.0,16.0,17.0,Zona Da Mata,Vermelho Novo - MG
2052,3360.0,3171154,2023,594,268.600006,67.300003,61.700001,98.500000,30.000000,5.200000,...,12.0,11.0,10.0,13.0,16.0,17.0,18.0,18.0,Zona Da Mata,Vermelho Novo - MG
2053,3157.8,3171154,2024,594,329.899994,227.500000,169.100006,71.199997,11.500000,2.300000,...,14.0,12.0,11.0,11.0,16.0,17.0,17.0,18.0,Zona Da Mata,Vermelho Novo - MG

In [27]:
len(df_dataset_vsemarea["Municipio"].unique())

158

In [28]:
df_dataset_vcomarea

,target,Municipio_id,Ano,altitude,Área colhida (Hectares),precipitacao (mm) 01,precipitacao (mm) 02,precipitacao (mm) 03,precipitacao (mm) 04,precipitacao (mm) 05,...,temperatura minima (ºC) 05,temperatura minima (ºC) 06,temperatura minima (ºC) 07,temperatura minima (ºC) 08,temperatura minima (ºC) 09,temperatura minima (ºC) 10,temperatura minima (ºC) 11,temperatura minima (ºC) 12,Mesorregião,Municipio
0,5702.0,3100302,2012,897,5280.0,18.700001,3.500000,4.500000,7.000000,176.100006,...,14.0,14.0,16.0,16.0,16.0,16.0,14.0,11.0,Zona Da Mata,Abre Campo - MG
1,5702.0,3100302,2013,897,5280.0,23.799999,4.100000,23.100000,26.000000,58.500000,...,15.0,16.0,16.0,17.0,17.0,17.0,13.0,11.0,Zona Da Mata,Abre Campo - MG
2,4320.0,3100302,2014,897,5400.0,33.500000,13.000000,8.700000,52.500000,106.000000,...,14.0,16.0,16.0,16.0,16.0,16.0,14.0,11.0,Zona Da Mata,Abre Campo - MG
3,6300.0,3100302,2015,897,5250.0,8.900000,53.200001,22.000000,7.100000,81.500000,...,14.0,16.0,16.0,17.0,17.0,16.0,14.0,12.0,Zona Da Mata,Abre Campo - MG
4,6300.0,3100302,2016,897,5250.0,17.700001,18.700001,10.000000,64.699997,65.599998,...,15.0,17.0,17.0,17.0,17.0,17.0,14.0,12.0,Zona Da Mata,Abre Campo - MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,3287.0,3171154,2020,594,2490.0,7.300000,6.300000,15.900000,42.200001,65.000000,...,16.0,17.0,17.0,18.0,18.0,17.0,15.0,11.0,Zona Da Mata,Vermelho Novo - MG
2050,2208.0,3171154,2021,594,2300.0,9.600000,17.000000,23.100000,34.299999,164.000000,...,17.0,17.0,17.0,18.0,17.0,17.0,14.0,12.0,Zona Da Mata,Vermelho Novo - MG
2051,2150.0,3171154,2022,594,2240.0,18.000000,2.300000,26.900000,27.000000,247.699997,...,16.0,17.0,16.0,18.0,18.0,17.0,15.0,11.0,Zona Da Mata,Vermelho Novo - MG
2052,3360.0,3171154,2023,594,2240.0,3.600000,4.300000,7.100000,55.700001,133.100006,...,17.0,16.0,17.0,17.0,18.0,17.0,15.0,12.0,Zona Da Mata,Vermelho Novo - MG
2053,3157.8,3171154,2024,594,2240.0,5.200000,18.100000,61.099998,26.600000,100.400002,...,17.0,18.0,18.0,18.0,18.0,18.0,16.0,14.0,Zona Da Mata,Vermelho Novo - MG

In [29]:
len(df_dataset_vcomarea["Municipio"].unique())

158

In [30]:
df_dadosclima

,Municipio,Base,time,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,...,CWD,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,WSDI
0,Abadia_dos_Dourados,Xavier,1995-01-01,21.86,19.40,35.06,26.13,9.0,10.0,20.0,...,12.0,7.0,1.0,6.31,29.47,55.97,1.0,594.63,512.05,6.0
1,Abadia_dos_Dourados,Xavier,1995-02-01,21.06,18.87,32.91,25.98,4.0,2.0,11.0,...,16.0,7.0,8.0,17.48,52.19,145.77,8.0,745.62,714.90,0.0
2,Abadia_dos_Dourados,Xavier,1995-03-01,21.66,17.86,33.25,27.54,2.0,7.0,18.0,...,4.0,3.0,1.0,8.30,33.78,56.84,1.0,691.49,658.59,0.0
3,Abadia_dos_Dourados,Xavier,1995-04-01,20.94,13.83,30.75,23.86,0.0,6.0,8.0,...,3.0,8.0,1.0,6.04,25.28,61.55,1.0,639.84,564.72,0.0
4,Abadia_dos_Dourados,Xavier,1995-05-01,19.73,12.07,31.07,24.34,3.0,11.0,4.0,...,4.0,16.0,2.0,20.92,65.81,120.63,2.0,503.95,351.03,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161104,Turvolandia,Xavier,2023-11-01,21.91,13.87,36.88,25.02,12.0,17.0,20.0,...,11.0,10.0,2.0,9.72,22.51,60.69,2.0,431.94,351.28,NaN
161105,Turvolandia,Xavier,2023-12-01,20.96,16.85,33.80,26.41,13.0,11.0,22.0,...,7.0,4.0,1.0,7.74,21.90,61.75,1.0,517.38,441.57,NaN
161106,Turvolandia,Xavier,2024-01-01,21.21,15.41,33.36,24.00,2.0,11.0,18.0,...,10.0,2.0,3.0,9.48,36.48,60.10,3.0,542.89,475.29,NaN
161107,Turvolandia,Xavier,2024-02-01,21.43,16.03,32.15,23.31,1.0,13.0,13.0,...,11.0,2.0,1.0,9.86,25.85,87.24,1.0,625.98,526.78,NaN
161108,Turvolandia,Xavier,2024-03-01,20.82,18.20,33.66,29.69,9.0,17.0,19.0,...,6.0,5.0,0.0,6.08,18.49,45.40,0.0,627.14,596.52,NaN

In [31]:
len(df_dadosclima["Municipio"].unique())

459

In [32]:
df_dataset_vcomarea = df_dataset_vcomarea.drop(['Municipio_id', 'altitude', 'Mesorregião'], axis=1)

In [33]:
df_dataset_vcomarea["Municipio"] = df_dataset_vcomarea["Municipio"].apply(lambda x: ''.join([c for c in unicodedata.normalize('NFKD', x.split(" - ")[0].replace("ç", "c")) if not unicodedata.combining(c)]))
df_dataset_vcomarea["Municipio"] = df_dataset_vcomarea["Municipio"].apply(lambda x: x.replace(" ", "_"))

In [34]:
df_dataset_vcomarea["target_por_area"] = df_dataset_vcomarea["target"] / df_dataset_vcomarea["Área colhida (Hectares)"]

In [35]:
df_dataset_vcomarea = df_dataset_vcomarea[df_dataset_vcomarea["Ano"] <= 2023]

In [36]:
df_dataset_vcomarea

,target,Ano,Área colhida (Hectares),precipitacao (mm) 01,precipitacao (mm) 02,precipitacao (mm) 03,precipitacao (mm) 04,precipitacao (mm) 05,precipitacao (mm) 06,precipitacao (mm) 07,...,temperatura minima (ºC) 05,temperatura minima (ºC) 06,temperatura minima (ºC) 07,temperatura minima (ºC) 08,temperatura minima (ºC) 09,temperatura minima (ºC) 10,temperatura minima (ºC) 11,temperatura minima (ºC) 12,Municipio,target_por_area
0,5702.0,2012,5280.0,18.700001,3.500000,4.500000,7.000000,176.100006,289.799988,381.799988,...,14.0,14.0,16.0,16.0,16.0,16.0,14.0,11.0,Abre_Campo,1.079924
1,5702.0,2013,5280.0,23.799999,4.100000,23.100000,26.000000,58.500000,279.000000,96.099998,...,15.0,16.0,16.0,17.0,17.0,17.0,13.0,11.0,Abre_Campo,1.079924
2,4320.0,2014,5400.0,33.500000,13.000000,8.700000,52.500000,106.000000,143.699997,422.299988,...,14.0,16.0,16.0,16.0,16.0,16.0,14.0,11.0,Abre_Campo,0.800000
3,6300.0,2015,5250.0,8.900000,53.200001,22.000000,7.100000,81.500000,195.100006,145.600006,...,14.0,16.0,16.0,17.0,17.0,16.0,14.0,12.0,Abre_Campo,1.200000
4,6300.0,2016,5250.0,17.700001,18.700001,10.000000,64.699997,65.599998,181.600006,172.800003,...,15.0,17.0,17.0,17.0,17.0,17.0,14.0,12.0,Abre_Campo,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2048,2473.0,2019,2290.0,6.100000,8.000000,45.799999,54.000000,128.300003,171.399994,185.199997,...,16.0,17.0,17.0,18.0,18.0,18.0,16.0,14.0,Vermelho_Novo,1.079913
2049,3287.0,2020,2490.0,7.300000,6.300000,15.900000,42.200001,65.000000,267.000000,186.899994,...,16.0,17.0,17.0,18.0,18.0,17.0,15.0,11.0,Vermelho_Novo,1.320080
2050,2208.0,2021,2300.0,9.600000,17.000000,23.100000,34.299999,164.000000,162.300003,185.199997,...,17.0,17.0,17.0,18.0,17.0,17.0,14.0,12.0,Vermelho_Novo,0.960000
2051,2150.0,2022,2240.0,18.000000,2.300000,26.900000,27.000000,247.699997,203.300003,170.399994,...,16.0,17.0,16.0,18.0,18.0,17.0,15.0,11.0,Vermelho_Novo,0.959821
2052,3360.0,2023,2240.0,3.600000,4.300000,7.100000,55.700001,133.100006,319.500000,287.799988,...,17.0,16.0,17.0,17.0,18.0,17.0,15.0,12.0,Vermelho_Novo,1.500000

In [37]:
len(df_dataset_vcomarea["Municipio"].unique())

158

In [38]:
df_dadosclima['time'] = pd.to_datetime(df_dadosclima['time'])
df_dadosclima["Mes"] = df_dadosclima["time"].dt.month
df_dadosclima["Ano"] = df_dadosclima["time"].dt.year

In [39]:
df_dadosclima = df_dadosclima.drop('time', axis=1)

In [40]:
df_dadosclima = df_dadosclima.loc[(df_dadosclima["Ano"] >= 2011) & (df_dadosclima["Ano"] <= 2023)]
# df_dadosclima = df_dadosclima[df_dadosclima["Ano"] >= 2011]

In [41]:
df_dadosclima = df_dadosclima.drop('Base', axis=1)

In [42]:
df_dadosclima

,Municipio,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,WN22,Frost,...,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,WSDI,Mes,Ano
192,Abadia_dos_Dourados,21.04,19.06,32.98,24.61,1.0,1.0,15.0,0.0,0.0,...,7.0,18.63,64.55,215.90,7.0,1148.58,998.05,0.0,1,2011
193,Abadia_dos_Dourados,21.13,18.72,32.30,28.99,0.0,3.0,25.0,0.0,0.0,...,1.0,5.58,26.26,55.67,1.0,1004.38,905.46,0.0,2,2011
194,Abadia_dos_Dourados,20.77,19.14,32.12,23.38,1.0,0.0,7.0,0.0,0.0,...,10.0,16.27,41.53,122.71,10.0,1132.64,1012.63,0.0,3,2011
195,Abadia_dos_Dourados,21.50,13.63,31.53,21.73,0.0,1.0,11.0,0.0,0.0,...,1.0,8.76,21.71,40.24,1.0,845.44,733.50,0.0,4,2011
196,Abadia_dos_Dourados,19.49,13.40,30.46,24.84,1.0,3.0,3.0,0.0,0.0,...,0.0,NaN,0.10,36.48,0.0,736.65,528.29,0.0,5,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161101,Turvolandia,17.73,11.09,33.80,16.67,9.0,19.0,4.0,0.0,0.0,...,0.0,3.54,8.08,17.78,0.0,83.62,73.33,NaN,8,2023
161102,Turvolandia,21.91,14.27,37.25,25.81,9.0,18.0,15.0,0.0,0.0,...,1.0,8.00,21.09,31.52,1.0,88.37,48.22,NaN,9,2023
161103,Turvolandia,21.11,16.75,33.15,23.59,2.0,23.0,17.0,0.0,0.0,...,3.0,9.85,33.45,70.69,2.0,351.15,159.92,NaN,10,2023
161104,Turvolandia,21.91,13.87,36.88,25.02,12.0,17.0,20.0,0.0,0.0,...,2.0,9.72,22.51,60.69,2.0,431.94,351.28,NaN,11,2023
161105,Turvolandia,20.96,16.85,33.80,26.41,13.0,11.0,22.0,0.0,0.0,...,1.0,7.74,21.90,61.75,1.0,517.38,441.57,NaN,12,2023

In [43]:
len(df_dadosclima["Municipio"].unique())

459

In [44]:
missing_cities_df = df_dataset_vcomarea[~df_dataset_vcomarea['Municipio'].isin(df_dadosclima['Municipio'])]
len(missing_cities_df['Municipio'].unique())

0

In [47]:
df_dadosclima = df_dadosclima.drop("WSDI", axis=1)
df_dadosclima = df_dadosclima.fillna(0)
df_dadosclima

,Municipio,TNx,TNn,TXx,TXn,TX90p,Tn90p,WD30,WN22,Frost,...,CDD,Wet20mm,Prec-Intensity,rx1day,rx5day,r95p,pr-wet-qrt,pr-dry-qrt,Mes,Ano
192,Abadia_dos_Dourados,21.04,19.06,32.98,24.61,1.0,1.0,15.0,0.0,0.0,...,3.0,7.0,18.63,64.55,215.90,7.0,1148.58,998.05,1,2011
193,Abadia_dos_Dourados,21.13,18.72,32.30,28.99,0.0,3.0,25.0,0.0,0.0,...,3.0,1.0,5.58,26.26,55.67,1.0,1004.38,905.46,2,2011
194,Abadia_dos_Dourados,20.77,19.14,32.12,23.38,1.0,0.0,7.0,0.0,0.0,...,1.0,10.0,16.27,41.53,122.71,10.0,1132.64,1012.63,3,2011
195,Abadia_dos_Dourados,21.50,13.63,31.53,21.73,0.0,1.0,11.0,0.0,0.0,...,5.0,1.0,8.76,21.71,40.24,1.0,845.44,733.50,4,2011
196,Abadia_dos_Dourados,19.49,13.40,30.46,24.84,1.0,3.0,3.0,0.0,0.0,...,31.0,0.0,0.00,0.10,36.48,0.0,736.65,528.29,5,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161101,Turvolandia,17.73,11.09,33.80,16.67,9.0,19.0,4.0,0.0,0.0,...,12.0,0.0,3.54,8.08,17.78,0.0,83.62,73.33,8,2023
161102,Turvolandia,21.91,14.27,37.25,25.81,9.0,18.0,15.0,0.0,0.0,...,10.0,1.0,8.00,21.09,31.52,1.0,88.37,48.22,9,2023
161103,Turvolandia,21.11,16.75,33.15,23.59,2.0,23.0,17.0,0.0,0.0,...,3.0,3.0,9.85,33.45,70.69,2.0,351.15,159.92,10,2023
161104,Turvolandia,21.91,13.87,36.88,25.02,12.0,17.0,20.0,0.0,0.0,...,10.0,2.0,9.72,22.51,60.69,2.0,431.94,351.28,11,2023
161105,Turvolandia,20.96,16.85,33.80,26.41,13.0,11.0,22.0,0.0,0.0,...,4.0,1.0,7.74,21.90,61.75,1.0,517.38,441.57,12,2023

In [49]:
df_result = pd.DataFrame()
municipios = df_dataset_vcomarea["Municipio"].unique()
municipios_clima = df_dadosclima["Municipio"].unique()
anos = [2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023]
meses = [
    {6: "Junho"},{7: "Julho"},{8: "Agosto"},{9: "Setembro"},
    {10: "Outubro"},{11: "Novembro"},{12: "Dezembro"},{1: "Janeiro"},
    {2: "Fevereiro"},{3: "Março"},{4: "Abril"},{5: "Maio"}
]
i = 0
for municipio in municipios:
    if municipio in municipios_clima:
        for ano in anos:
            df_result.loc[i, "Municipio"] = municipio
            df_result.loc[i, "Ano"] = ano
            
            df_result.loc[i, "target_por_area"] = df_dataset_vcomarea.loc[
                (df_dataset_vcomarea["Municipio"] == municipio) &
                (df_dataset_vcomarea["Ano"] == ano), "target_por_area"
            ].iloc[0]

            colunas_clima = list(df_dadosclima.columns)
            for column in ["Municipio", "Mes", "Ano"]: colunas_clima.remove(column)
            
            for mes in meses:
                mes_num = list(mes.keys())[0]
                if mes_num >= 6:
                    df_clima = df_dadosclima.loc[
                        (df_dadosclima["Municipio"] == municipio) &
                        (df_dadosclima["Ano"] == ano-1) &
                        (df_dadosclima["Mes"] == mes_num)
                    ]

                    df_result.loc[i, f"preco_{mes_num}"] = df_preco.loc[
                        (df_preco["Ano"] == ano-1),
                        f"{list(mes.values())[0]}"
                    ].iloc[0]
                else:
                    df_clima = df_dadosclima.loc[
                        (df_dadosclima["Municipio"] == municipio) &
                        (df_dadosclima["Ano"] == ano) &
                        (df_dadosclima["Mes"] == mes_num)
                    ]

                    df_result.loc[i, f"preco_{mes_num}"] = df_preco.loc[
                        (df_preco["Ano"] == ano),
                        f"{list(mes.values())[0]}"
                    ].iloc[0]
                
                for column in colunas_clima:
                    df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]

            i += 1

/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"preco_{mes_num}"] = df_preco.loc[
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result.loc[i, f"{column}_{mes_num}"] = df_clima[column].iloc[0]
/tmp/ipykernel_12062/1835809023.py:51: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [50]:
df_result

,Municipio,Ano,target_por_area,preco_6,TNx_6,TNn_6,TXx_6,TXn_6,TX90p_6,Tn90p_6,...,Wetdays_5,CWD_5,CDD_5,Wet20mm_5,Prec-Intensity_5,rx1day_5,rx5day_5,r95p_5,pr-wet-qrt_5,pr-dry-qrt_5
0,Abre_Campo,2012.0,1.079924,"305,53",14.61,7.91,27.16,19.43,2.0,1.0,...,9.0,3.0,8.0,1.0,10.00,29.44,56.81,1.0,243.97,193.35
1,Abre_Campo,2013.0,1.079924,"178,69",16.92,9.22,27.07,20.67,2.0,11.0,...,8.0,7.0,17.0,0.0,9.30,17.37,49.40,0.0,407.82,350.25
2,Abre_Campo,2014.0,0.800000,"130,72",16.11,9.80,28.48,20.56,1.0,6.0,...,3.0,3.0,24.0,0.0,1.98,2.92,5.94,0.0,176.90,147.95
3,Abre_Campo,2015.0,1.200000,"172,37",15.68,8.37,26.65,21.73,0.0,4.0,...,8.0,3.0,8.0,2.0,13.77,38.89,58.17,2.0,248.73,206.43
4,Abre_Campo,2016.0,1.200000,"151,12",16.25,7.02,28.37,18.94,2.0,5.0,...,3.0,1.0,13.0,0.0,3.69,7.33,32.07,0.0,133.41,115.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1891,Vermelho_Novo,2019.0,1.079913,"123,18",17.06,10.35,27.72,20.37,2.0,8.0,...,8.0,4.0,12.0,0.0,5.56,13.13,23.84,0.0,227.80,173.99
1892,Vermelho_Novo,2020.0,1.320080,"110,88",17.20,9.32,30.05,23.55,5.0,13.0,...,7.0,3.0,7.0,0.0,6.82,18.58,22.41,1.0,572.00,287.73
1893,Vermelho_Novo,2021.0,0.960000,"98,75",17.44,8.37,28.75,21.81,5.0,5.0,...,2.0,1.0,15.0,0.0,5.50,9.81,9.92,0.0,373.57,107.24
1894,Vermelho_Novo,2022.0,0.959821,"158,15",17.25,8.11,28.92,21.35,4.0,3.0,...,3.0,3.0,24.0,0.0,1.87,2.79,5.74,0.0,364.72,82.40
1895,Vermelho_Novo,2023.0,1.500000,"248,68",17.42,6.95,29.74,21.21,9.0,3.0,...,5.0,3.0,11.0,0.0,2.94,5.16,34.82,0.0,107.33,94.44

In [51]:
for mes in meses:
    mes_num = list(mes.keys())[0]
    df_result[f"preco_{mes_num}"] = df_result[f"preco_{mes_num}"].str.replace(',', '.', regex=False).astype('float')

In [52]:
df_result.to_excel("Dados para correlação v3 - Xavier.xlsx", index=False)

In [23]:
df_corr = pd.DataFrame()

In [24]:
for ano in df_result["Ano"].unique():
    df_ano = df_result[df_result["Ano"] == ano]
    numeric_cols = df_ano.select_dtypes(include=['float64', 'int64']).columns
    corr_matrix = df_ano[numeric_cols].corr()
    df_corr.loc[:, ano] = corr_matrix["target"]

In [16]:
for municipio in df_result["Municipio"].unique():
    df_municipio = df_result[df_result["Municipio"] == municipio]
    numeric_cols = df_municipio.select_dtypes(include=['float64', 'int64']).columns
    corr_matrix = df_municipio[numeric_cols].corr()
    df_corr.loc[:, municipio] = corr_matrix["target"]

C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]
C:\Users\josue\AppData\Local\Temp\ipykernel_11812\3693950566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_corr.loc[:, municipio] = corr_matrix["target"]

In [25]:
df_corr.fillna(0, inplace=True)

In [26]:
df_corr.loc[:, "MEDIA"] = df_corr.mean(axis=1)
df_corr.loc[:, "DP"] = df_corr.std(axis=1)

In [27]:
df_corr.to_excel("Correlação de variáveis por ano - Xavier.xlsx")

In [28]:
df_corr

,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,MEDIA,DP
Ano,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
target,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
preco_6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
TNx_6,0.032437,0.016536,-0.078329,-0.095194,-0.060121,-0.132201,0.016227,-0.120225,-0.044223,-0.065891,0.010130,-0.031394,-0.046021,0.053466
TNn_6,-0.079799,0.030786,0.171024,-0.038728,0.069601,-0.042487,-0.033094,-0.028333,-0.079840,0.091987,-0.068541,0.167780,0.013363,0.087632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rx5day_5,-0.242743,0.084868,-0.068545,0.101750,-0.250551,0.008380,0.108444,0.225310,-0.043598,-0.159346,0.041646,-0.263212,-0.038133,0.154759
r95p_5,-0.251209,0.113403,-0.149075,0.108499,-0.102853,0.023515,0.120774,0.149544,-0.062863,-0.050489,0.206666,-0.050721,0.004599,0.132153
pr-wet-qrt_5,0.014771,0.153065,0.268565,0.276778,0.037768,0.006678,-0.044336,0.205162,0.145951,-0.066860,0.177986,0.063450,0.103248,0.112347
pr-dry-qrt_5,-0.000665,0.187715,0.236241,0.295055,0.015270,-0.022475,-0.075166,0.199883,-0.154203,-0.074814,-0.070653,0.044705,0.048408,0.139252
WSDI_5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [29]:
colunas_clima = list(df_dadosclima.columns)
for column in ["Municipio", "Base", "Mes", "Ano"]: colunas_clima.remove(column)

variable_groups = dict()
for column in colunas_clima:
    variable_groups[column] = [f"{column}_{list(mes.keys())[0]}" for mes in meses]
variable_groups["preco"] = [f"preco_{list(mes.keys())[0]}" for mes in meses]

fig = go.Figure()

all_vars_in_order = [var for group in variable_groups.values() for var in group]
unique_variables = sorted(list(set(all_vars_in_order)))

for var in unique_variables:
    fig.add_trace(
        go.Bar(
            x=df_corr.columns.tolist(),
            y=df_corr.loc[var],
            name=var,
            visible=False
        )
    )


buttons = []
for group_name, vars_in_group in variable_groups.items():
    visibility = [trace.name in vars_in_group for trace in fig.data]
    
    buttons.append(
        dict(
            label=group_name,
            method='restyle',
            args=[{'visible': visibility}]
        )
    )

fig.update_layout(
    updatemenus=[
        dict(
            active=0,
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1.14,
            xanchor="right",
            y=1.25,
            yanchor="top"
        )
    ],
    width=1200,
    height=600,
    title_text="Correlação de variáveis por ano",
    xaxis_title="Ano",
    yaxis_title="Correlação",
    barmode='group',
    xaxis=dict(
        rangeslider=dict(
            visible=True
        ),
        type="category"
    )
)

initial_group = list(variable_groups.keys())[0]
for trace in fig.data:
    if trace.name in variable_groups[initial_group]:
        trace.visible = True

fig.show()
fig.write_html("Correlação de variáveis por ano - Xavier.html")